region             = "ap-south-2"
mgmt_vpc_cidr      = "10.0.0.0/16"
mgmt_subnet_cidrs  = "10.0.1.0/24"
mgmt_instance_type = "t3.medium"
key_name           = "Hyd-kp"
private_key_path   = "C:/Users/prabh/Desktop/Hyd-kp.pem"